name: Build stand-aloneexecutables

on:
  push:
    branches:
      - main      

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up script permissions
      run: chmod +x ./generate_executable.sh

    - name: Execute script
      run: ./generate_executable.sh
